# Generated by Django 2.2.12 on 2022-11-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='komik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodekomik', models.CharField(max_length=8)),
                ('namakomik', models.CharField(max_length=120)),
                ('penerbit', models.CharField(max_length=50)),
                ('stockkomik', models.IntegerField()),
                ('hargakomik', models.BigIntegerField()),
            ],
        ),
    ]
